name: Python-test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step#1 check out  the code from the git repo
      - name: Check out code
        uses: actions/checkout@v2

      # Step#2 Setup python environement
      - name: Step up Python
        uses: action/setup-python@v2
        with:
          python-version: '3.8'

      # Step#3 Install dependencies
      - name: Install dependencies
        run: |
          python -m pip intall --upgrade pip
          pip install -r requirements.txt

      # Step#4 Run tests
      - name: Run test
        run: pytest
